import type { Speaker } from './speaker';
import { Track } from './speaker';

export const SpeakersData: Speaker[] = [
    {
        name: 'Marius Străjeru',
        photo: '/assets/speakers/mm24ro/mariusstrajeru.jpg',
        company: 'Arnia',
        companyTitle: undefined,
        track: Track.Technical,
        featured: false,
    },
    {
        name: 'Ivan Chepurnyi',
        photo: '/assets/speakers/mm24ro/ivanchepurnyi.jpg',
        company: 'EcomDev',
        companyTitle: undefined,
        track: Track.Technical,
        featured: true,
    },
    {
        name: 'John Hughes',
        photo: '/assets/speakers/mm24ro/johnhughes.jpg',
        company: 'Hyvä',
        companyTitle: 'VP Enterprise Solutions',
        track: Track.Technical,
        featured: true,
    },
    {
        name: 'Mathias Schreiber',
        photo: '/assets/speakers/mm24ro/mathiasschreiber.jpg',
        company: 'Magento Asociation',
        companyTitle: undefined,
        track: Track.Technical,
        featured: false,
    },
    {
        name: 'Denisa Constantinoiu',
        photo: '/assets/speakers/mm24ro/denisaconstantinoiu.jpg',
        company: 'Kollab',
        companyTitle: 'Social Media Expert & Co-Founder',
        track: Track.Business,
        featured: true,
    },
    {
        name: 'Iulia Greab',
        photo: '/assets/speakers/mm24ro/iuliagreab.jpg',
        company: 'DoAds',
        companyTitle: 'Facebook & Instagram Ads Expert',
        track: Track.Business,
        featured: true,
    },
    {
        name: 'Alin Alexandru',
        photo: '/assets/speakers/mm24ro/alinalexandru.jpg',
        company: 'Innobyte',
        companyTitle: 'CTO',
        track: Track.Technical,
        featured: false,
    },
    {
        name: 'Bogdan Iftemie',
        photo: '/assets/speakers/mm24ro/bogdaniftemie.jpg',
        company: 'PayPo',
        companyTitle: 'Business Development Director',
        track: Track.Business,
        featured: false,
    },
    {
        name: 'Bogdan Marin',
        photo: '/assets/speakers/mm24ro/bogdanmarin.jpg',
        company: 'Adobe',
        companyTitle: 'Enginnering Manager',
        track: Track.Business,
        featured: false,
    },
    {
        name: 'Valentin Bolboacă',
        photo: '/assets/speakers/mm24ro/valentinbolboaca.jpg',
        company: 'Klain',
        companyTitle: 'CEO',
        track: Track.Business,
        featured: false,
    },
    {
        name: 'Nick Muldoon',
        photo: '/assets/speakers/mm24ro/nickmuldoon.jpg',
        company: 'JH',
        companyTitle: 'Customer Success Manager',
        track: Track.Business,
        featured: false,
    },
    {
        name: 'Piotr Pantkowski',
        photo: '/assets/speakers/mm24ro/piotrpantkowski.jpg',
        company: 'cyber_Folks',
        companyTitle: undefined,
        track: Track.Business,
        featured: false,
    },
    {
        name: 'Dan Ilie',
        photo: '/assets/speakers/mm24ro/danilie.jpg',
        company: 'Adobe',
        companyTitle: 'Senior Developer',
        track: Track.Technical,
        featured: false,
    },
    {
        name: 'Valentin Sandu',
        photo: '/assets/speakers/mm24ro/valentinsandu.jpg',
        company: 'Reverse Seven',
        companyTitle: undefined,
        track: Track.Technical,
        featured: false,
    },
    {
        name: 'Dmitriy Gallamov',
        photo: '/assets/speakers/mm24ro/dmitriygallamov.jpg',
        company: 'Developers Alliance',
        companyTitle: undefined,
        track: Track.Technical,
        featured: false,
    },
    {
        name: 'Kuba Zwolinski',
        photo: '/assets/speakers/mm24ro/kubazwolinski.jpg',
        company: 'SnowDog',
        companyTitle: 'Founder & CEO',
        track: Track.Business,
        featured: false,
    },
    {
        name: 'Andrei Leica',
        photo: '/assets/speakers/mm24ro/andreileica.jpg',
        company: 'Arnia',
        companyTitle: 'Lead AI Research Engineer',
        track: Track.Technical,
        featured: false,
    },
    {
        name: 'Jakub Wilkler',
        photo: '/assets/speakers/mm24ro/jakubwilkler.jpg',
        company: 'Q-Solutions Studio',
        companyTitle: 'CEO',
        track: Track.Technical,
        featured: false,
    },
    {
        name: 'Sorin Bărnuțiu',
        photo: '/assets/speakers/mm24ro/sorinbarnutiu.jpg',
        company: 'Baldwin',
        companyTitle: 'Senior Front-end Developer',
        track: Track.Technical,
        featured: false,
    },
    {
        name: 'Adrian Ilovan',
        photo: '/assets/speakers/mm24ro/adrianilovan.jpg',
        company: 'Netlogiq',
        companyTitle: 'CEO',
        track: Track.Business,
        featured: false,
    },
];