import type { Speaker } from './speaker';
import { Track } from './speaker';

export const SpeakersData: Speaker[] = [
    {
        name: 'Ray Bogman',
        photo: '/assets/speakers/mm23ro/raybogman.jpg',
        company: 'Adobe',
        companyTitle: 'Head of Commerce, Customer Engineering EMEA',
        track: Track.Technical,
        featured: true,
    },
    {
        name: 'Marius Străjeru',
        photo: '/assets/speakers/mm23ro/mariusstrajeru.jpg',
        company: 'Arnia',
        companyTitle: undefined,
        track: Track.Technical,
        featured: true,
    },
    {
        name: 'Răzvan Bradea',
        photo: '/assets/speakers/mm23ro/razvanbradea.jpg',
        company: 'Adobe',
        companyTitle: undefined,
        track: Track.Technical,
        featured: false,
    },
    {
        name: 'Ivan Chepurnyi',
        photo: '/assets/speakers/mm23ro/ivanchepurnyi.jpg',
        company: 'EcomDev',
        companyTitle: undefined,
        track: Track.Technical,
        featured: false,
    },
    {
        name: 'Łukasz Bajsarowicz',
        photo: '/assets/speakers/mm23ro/lukaszbajsarowicz.jpg',
        company: 'SwiftOtter',
        companyTitle: undefined,
        track: Track.Technical,
        featured: false,
    },
    {
        name: 'Mathias Schreiber',
        photo: '/assets/speakers/mm23ro/mathiasschreiber.jpg',
        company: 'Meet Magento Asociation',
        companyTitle: undefined,
        track: Track.Technical,
        featured: true,
    },
    {
        name: 'Roman Bălțeannu',
        photo: '/assets/speakers/mm23ro/romanbalteanu.jpg',
        company: 'Google',
        companyTitle: undefined,
        track: Track.Business,
        featured: false,
    },
    {
        name: 'Ciprian Cazacu',
        photo: '/assets/speakers/mm23ro/cipriancazacu.jpg',
        company: 'easySales',
        companyTitle: 'CEO and co-founder',
        track: Track.Business,
        featured: false,
    },
    {
        name: 'Alexandru Balaci',
        photo: '/assets/speakers/mm23ro/alexandrubalaci.jpg',
        company: 'Mokka',
        companyTitle: 'CEO',
        track: Track.Business,
        featured: false,
    },
    {
        name: 'Vlad Marincaș',
        photo: '/assets/speakers/mm23ro/vladmarincas.jpg',
        company: 'Aqurate',
        companyTitle: 'CEO and co-founder',
        track: Track.Business,
        featured: true,
    },
    {
        name: 'Artur Pajkert',
        photo: '/assets/speakers/mm23ro/arturpajkert.jpg',
        company: 'cyber_Folks',
        companyTitle: undefined,
        track: Track.Business,
        featured: false,
    },
    {
        name: 'Cosmin Costea',
        photo: '/assets/speakers/mm23ro/cosmincostea.jpg',
        company: 'theMarketer',
        companyTitle: 'VP of Sales CEE',
        track: Track.Business,
        featured: false,
    },
    {
        name: 'Călin Petrar',
        photo: '/assets/speakers/mm23ro/calinpetrar.jpg',
        company: 'Times New Roman',
        companyTitle: undefined,
        track: Track.Technical,
        featured: false,
    },
    {
        name: 'Sorin Trifu',
        photo: '/assets/speakers/mm23ro/sorintrifu.jpg',
        company: 'HOLD Marketing',
        companyTitle: undefined,
        track: Track.Business,
        featured: false,
    },
    {
        name: 'Cristian Glăvan',
        photo: '/assets/speakers/mm23ro/cristianglavan.jpg',
        company: 'Zitec',
        companyTitle: undefined,
        track: Track.Technical,
        featured: false,
    },
    {
        name: 'George Mușat',
        photo: '/assets/speakers/mm23ro/georgemusat.jpg',
        company: 'Zitec',
        companyTitle: undefined,
        track: Track.Technical,
        featured: false,
    },
    {
        name: 'Paul Apostu',
        photo: '/assets/speakers/mm23ro/paulapostu.jpg',
        company: 'Ecommerce-Today',
        companyTitle: undefined,
        track: Track.Business,
        featured: false,
    },
    {
        name: 'Valentin Sandu',
        photo: '/assets/speakers/mm23ro/valentinsandu.jpg',
        company: 'R7 Digital Commerce',
        companyTitle: undefined,
        track: Track.Technical,
        featured: false,
    },
    {
        name: 'Sorin Dumitrescu',
        photo: '/assets/speakers/mm23ro/sorindumitrescu.jpg',
        company: 'Bunnyshell',
        companyTitle: undefined,
        track: Track.Technical,
        featured: false,
    },
    {
        name: 'Alin Alexandru',
        photo: '/assets/speakers/mm23ro/alinalexandru.jpg',
        company: 'Innobyte',
        companyTitle: 'CTO',
        track: Track.Technical,
        featured: false,
    },
    {
        name: 'Attila Kiraly',
        photo: '/assets/speakers/mm23ro/attilakiraly.jpg',
        company: 'SEO 365',
        companyTitle: undefined,
        track: Track.Business,
        featured: false,
    },
];