import type { Sponsor } from './sponsor';
import { SponsorPackage } from './sponsor';

export const SponsorsData: Sponsor[] = [
    {
        name: 'cyber_Folks',
        logo: 'assets/sponsors/cyberfolks.svg',
        url: 'https://cyberfolks.ro/',
        package: SponsorPackage.Platinum,
        description: 'cyber_Folks is a web hosting and e-commerce company that offers innovative technological solutions supported by exceptional support, to ensure the growth of businesses online.',
    },
    {
        name: 'PayPo',
        logo: 'assets/sponsors/paypo.svg',
        url: 'https://paypo.ro/',
        package: SponsorPackage.Gold,
        description: 'Paypo este o companie fintech fondata in 2016 in Polonia, lider regional in CEE pe piata solutiilor BNPL. Prin integrarea metodei de plata PayPo, comerciantii online isi pot creste afacerea si conversia, prin cresterea valorii medii a cosului (AOV) si prin scaderea ratei de abandon a cosului.',
    },
    {
        name: 'Apsis',
        logo: 'assets/sponsors/apsisai.svg',
        url: 'https://apsis.ai/',
        package: SponsorPackage.Gold,
        description: 'Apsis AI is an AI-powered Visual Search to remove slow and inaccurate textual searches and promote product discovery across domains, from real world images to shops',
    },
    {
        name: 'Innobyte',
        logo: 'assets/sponsors/innobyte.svg',
        url: 'https://innobyte.com',
        package: SponsorPackage.Gold,
        description: 'Innobyte is a strategic e-commerce partner that delivers flawless execution and ongoing counselling for mid and large-scale businesses. We offer a complex range of services to help companies to implement, launch and grow a successful e-commerce platform.',
    },
    // {
    //     name: 'SoftLead',
    //     logo: 'assets/sponsors/softlead.svg',
    //     url: 'https://softlead.ro/',
    //     package: SponsorPackage.Silver,
    //     description: "Softlead helps companies in the digital transformation process by identifying the most suitable partners across all industries",
    // },
    // {
    //     name: 'theMarketer',
    //     logo: 'assets/sponsors/themarketer.svg',
    //     url: 'https://themarketer.com/',
    //     package: SponsorPackage.Silver,
    //     description: "theMarketer is an email and loyalty marketing platform enabling businesses to streamline their marketing processes, optimize their resources, and boost customer lifetime value using a suite of powerful features",
    // },
    // {
    //     name: 'We as Web',
    //     logo: 'assets/sponsors/weasweb.svg',
    //     url: 'https://www.weasweb.com/',
    //     package: SponsorPackage.Silver,
    //     description: "We as Web provides top-notch team augmentation and outsourcing services to companies in various industries who are in search of talented experts for short or long term projects.",
    // },
    // {
    //     name: 'Nexttech',
    //     logo: 'assets/sponsors/nexttech.svg',
    //     url: 'https://nexttech.ro',
    //     package: SponsorPackage.Gold,
    //     description: 'Romanian privately owned software development and IT consulting company specialized in nearshore and offshore digital transformation with functional expertise in E-commerce, Trading, Banking, Insurance, and Automotive industry.',
    // },
    // {
    //     name: 'Hyvä',
    //     logo: '/assets/sponsors/hyva.svg',
    //     url: 'https://hyva.io/',
    //     package: SponsorPackage.Gold,
    //     description: 'Hyvä is the built-from-scratch Magento 2 front end that makes your online store ultra-fast and performant. Hyvä saves you tons of development time and has the fastest ROI in the market, as your traffic, bounce rate and conversion rates are improved.',
    // },
    // {
    //     name: 'Bunnyshell',
    //     logo: '/assets/sponsors/bunnyshell.svg',
    //     url: 'https://www.bunnyshell.com/',
    //     package: SponsorPackage.Silver,
    //     description: "Bunnyshell's DevOps platform simplifies Magento development and testing with on-demand cloud environments for all your teams.",
    // },
    // {
    //     name: 'ZentoShop',
    //     logo: 'assets/sponsors/zentoshop.svg',
    //     url: 'https://www.zentoshop.com',
    //     package: SponsorPackage.Organizer,
    //     description: 'Zento is a Software-as-a-Service (SaaS) solution built on top of Magento 2 and offers fully managed eCommerce solutions with state-of-the-art Cloud hosting to medium and large merchants.',
    // },
    {
        name: 'MageFan',
        logo: '/assets/sponsors/magefan.svg',
        url: 'https://www.magefan.com/',
        package: SponsorPackage.Silver,
        description: "Magefan company is about high-quality e-commerce solutions for Magento 2 you can trust.",
    },
    {
        name: 'Baldwin',
        logo: 'assets/sponsors/baldwin.svg',
        url: 'https://www.baldwin.agency/?utm_source=https://ro.meet-magento.com/&utm_medium=referral&utm_content=sponsors',
        package: SponsorPackage.Silver,
        description: 'From building online stores and developing software solutions to marketing them using a wide range of online promotion tools, Baldwin is the ideal business partner that can guarantee high sales volumes and excellent customer retention rates.',
    },
    {
        name: 'Clever++',
        logo: 'assets/sponsors/clever.svg',
        url: 'https://cleverplusplus.com/',
        package: SponsorPackage.Silver,
        description: "Clever++ is a Magento provider and solution specialist.",
    },
    {
        name: 'cyber_Folks',
        logo: 'assets/sponsors/cyberfolks.svg',
        url: 'https://cyberfolks.ro/',
        package: SponsorPackage.Organizer,
        description: 'cyber_Folks is a web hosting and e-commerce company that offers innovative technological solutions supported by exceptional support, to ensure the growth of businesses online.',
    },
];